IDE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('IDEApp/', include('IDEApp.urls'))
]

IDEApp/urls.py
from django.urls import path, include
from .views import codeit, IDEViewSet
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register(r'codes', views.IDEViewSet)

urlpatterns = [
    # path('', views.index, name='index'),
    path('codeit/', views.codeit, name='codeit'),
    path('run/', views.codeRun, name='run'),
    path('submit/', views.codeSubmit, name='submit'),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

IDEApp/models.py
from django.db import models

import subprocess
import os
import time
import sys
# Create your models here.


class Problem(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20)
    defination = models.TextField()

    def __str__(self):
        return '%s' % (self.title)


class TestCases(models.Model):
    problem_id = models.ForeignKey(Problem, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    inp = models.TextField()
    out = models.TextField()

    def __str__(self):
        return '%s %s' % (self.problem_id, self.id)


class Submission(models.Model):
    id = models.AutoField(primary_key=True)
    problem_id = models.ForeignKey(Problem, on_delete=models.CASCADE)
    code = models.TextField()
    result = models.TextField(null=True)


class IDE(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    code = models.TextField()
    inp = models.TextField(null=True)
    output = models.TextField(null=False, default="No ouput")

    def showOutput(self):
        path = self.makeFile(self.title, self.code)

        self.output = self.runCpp(path)

    def save(self, *args, **kwargs):
        self.showOutput()
        super().save(*args, **kwargs)

    def makeFile(self, name, code):
        name = name.replace(" ", "_")
        name = "G:\\SEM - 4\\Python\\Django_framework\\IDE\\IDE\\IDEApp\\Progs\\"+name+".cpp"
        with open(name, 'w') as f:
            code = code.replace("\r", "")
            f.write(code)
        return name

    def runCpp(self, path):
        runs = subprocess.run(
            ['g++', '-D', 'AUTO', '-O2', '-std=c++14', '-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC', '-Wall', path, '-o', 'a.exe'], text=True, capture_output=True)
        if runs.returncode != 0:
            return "error!!!"
        else:
            data, temp = os.pipe()
            ins = self.inp
            ins = ins.strip()
            os.write(temp, bytes(str(ins).encode()))
            os.close(temp)
            start_time = time.process_time()
            s = subprocess.check_output(
                ['a.exe'], stdin=data, shell=True)
            output = s.decode("utf-8")
            output = output.replace("\r", "")
            return output

    def __str__(self):
        return str(self.title)

IDEApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.conf import settings

from .IDEForm import Editor
from .models import IDE, Submission, Problem, TestCases
from .serializers import IDESerializer
from rest_framework import viewsets

import json
import subprocess
import os
import time
import sys
# Create your views here.


def index(request):
    return HttpResponse(runCpp('G:/SEM - 4/Python/Django_framework/IDE/IDE/IDEApp/Progs/a.cpp'))


class IDEViewSet(viewsets.ModelViewSet):
    queryset = IDE.objects.all().order_by('id')
    print("exe")
    serializer_class = IDESerializer


def codeSubmit(request):
    text = ""
    response_data = {}
    response_data['msg'] = "error"
    print("code Run")
    if request.method == "POST":
        print(request.POST['code'])

        path = makeFile(request.POST['title'].rstrip(), request.POST['code'])
        inputs = ""
        problems = Problem.objects.all()[0]
        response_data['msg'] = "success"
        print(response_data)
        print(TestCases.objects.filter(problem_id=problems))
        k = 0
        answer = ""
        flag = False
        debug_msg = ""
        # for i in problems.testcases_set.all():
        for i in TestCases.objects.filter(problem_id=problems):
            text = runCpp(path, i.inp)
            k += 1
            answer += "#input :" + str(k)+"\n"+i.inp
            answer += "\nOutput:\n" + text
            answer += "\nAnswer:\n" + i.out + "\n\n"
            if (str(i.out).strip() != text.strip()):
                flag = True
                debug_msg = "Wrong Answer\n"
                debug_msg += "#input :" + str(k)+"\n"+i.inp
                debug_msg += "\nOutput:\n" + text
                debug_msg += "\nAnswer:\n" + i.out + "\n\n"
                debug_msg.replace("\n", "<br/>")
            break
            print(i.inp)
            print(i.out)
            print(text)
        # return JsonResponse(response_data)
        if (flag):
            response_data['out'] = debug_msg
        else:
            response_data['out'] = "Accepted"
        form = Submission(problem_id=problems,
                          code=request.POST['code'], result=answer)
        form.save()
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )


def codeRun(request):
    text = ""
    response_data = {}
    response_data['msg'] = "error"
    print("code Run")
    if request.method == "POST":
        path = makeFile(request.POST['title'].rstrip(), request.POST['code'])
        inputs = ""
        print(request.POST.get('chk_input'))
        if request.POST.get('chk_input') == '1':
            inputs = (str(request.POST['inp'])).strip()
            print(inputs)
        text = runCpp(path, inputs)
        text = text.strip()
        response_data['out'] = text
        response_data['msg'] = "success"
        print(response_data)
        # return JsonResponse(response_data)
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    # text = ""
    # response_data = {}
    # response_data['msg'] = "error"
    # print("code Run")
    # if request.method == "POST":
    #     path = makeFile(request.POST['title'].rstrip(), request.POST['code'])
    #     inputs = ""
    #     print(request.POST.getlist('chk_input'))
    #     if request.POST.get('chk_input') == '1':
    #         inputs = (str(request.POST['input'])).strip()
    #     text = runCpp(path, inputs)
    #     text = text.strip()
    #     response_data['out'] = text
    #     response_data['msg'] = "success"
    #     print(response_data)
    #     return JsonResponse(response_data)
    # return JsonResponse(response_data)


def codeit(request):
    print(settings.BASE_DIR)
    print(settings.MEDIA_ROOT)
    text = "123\n456"
    form = {"hello": "to"}
    return render(request, 'IDE/index.html')

# def codeit(request):
#     # form = Editor()
#     text = ""
#     if request.method == "POST":
#         # form = Editor(request.POST)
#         # print(request.POST['code'])
#         path = makeFile(request.POST['title'].rstrip(), request.POST['code'])
#         text = runCpp(path, (str(request.POST['inp'])).strip())
#         # print(form)
#         # if form.is_valid():
#         #     post = form.save()
#         #     form.save()
#         #     print("ID"+str(post.id))
#     # else:
#         # form = Editor()
#         # text = IDE.objects.all()
#     text = text.strip()
#     # print(repr(request.POST['inp']))
#     print(text.split('\n'))
#     form = {"hello": "to"}
#     return render(request, 'IDE/index.html', {'form': form, "text": {"lines": text.split('\n')}})


def makeFile(name, code):
    name = name.replace(" ", "_")
    name = settings.SUBMISSION_ROOT+name+".cpp"
    with open(name, 'w') as f:
        code = code.replace("\r", "")
        f.write(code)
    return name


def compileCpp(path):
    runs = subprocess.run(
        ['g++', '-D', 'AUTO', '-O2', '-std=c++14', '-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC', '-Wall', path, '-o', 'a.o'], text=True, capture_output=True)
    return not runs.returncode


def runCpp(path, inp):
    runs = subprocess.run(
        ['g++', '-D', 'AUTO', '-O2', '-std=c++14', '-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC', '-Wall', path, '-o', os.path.join(settings.SUBMISSION_ROOT, '/a.o')], text=True, capture_output=True)
    if runs.returncode != 0:
        return "error!!!"
    else:
        data, temp = os.pipe()
        ins = inp
        os.write(temp, bytes(str(ins).encode()))
        os.close(temp)
        start_time = time.process_time()
        s = subprocess.check_output(
            [os.path.join(settings.SUBMISSION_ROOT, '/a.o')], stdin=data, shell=True)
        output = s.decode("utf-8")
        output = output.replace("\r", "")
        return output

IDEApp/templates/IDE/aceTrial.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>ACE in Action</title>
    <style type="text/css" media="screen">
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        #editor {
            position: relative;
            /* grid: 500px; */
            height: 500px;
            width: 900px;
            flex: 1;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            border: 1px solid black;
        }
    </style>
</head>

<body>
    <div class="editor-blk">
        <div id="editor">
        </div>
    </div>
    <button id="submit" onclick="getValue()">Submit</button>
    <script src="../../static/JS/ace.js" type="text/javascript" charset="utf-8"></script>
    <script>
        // document.getElementById("editor").innerText = code;
        var editor = ace.edit("editor");
        editor.setTheme("ace/theme/twilight");
        editor.session.setMode("ace/mode/c_cpp");
        function getValue() {
            console.log(editor.getValue());
        }
    </script>
</body>

</html>

IDEApp/templates/IDE/base.html
{% load static %}
<html>

<head>
    <title>IDE</title>
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <script src="https://kit.fontawesome.com/c85142f965.js" crossorigin="anonymous"></script>
    <!-- <script src="../../static/JS/ace.js" type="text/javascript" charset="utf-8"></script> -->
    <script src="{% static 'JS/src-noconflict/ace.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'JS/src-noconflict/ext-language_tools.js' %}" type="text/javascript"
        charset="utf-8"></script>
    <!-- bootstrap cdn -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <!-- bootstrap cdn end -->

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/index.css' %}">

    <script type="text/javascript" src="{% static 'codemirror/lib/codemirror.js' %}"></script>
    <script type="text/javascript" src="{% static 'codemirror/mode/python/python.js' %}"></script>
    <script type="text/javascript" src="{% static 'codemirror/mode/clike/clike.js' %}"></script>
    <script type="text/javascript" src="{% static 'codemirror/mode/xml/xml.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'codemirror/lib/codemirror.css' %}">
    <link type="text/javascript" href="{% static 'codemirror/keymap/sublime.js' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.52.2/theme/monokai.min.css">
</head>

<body>
    <div class="page-header">
        <a href="{% url 'codeit' %}" class="top-menu"></a>
        <h1><a href="/">Code it!!</a></h1>
    </div>
    <div class="content container">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

IDEApp/templates/IDE/form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
    <form>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
            </div>
            <div class="form-group col-md-6">
                <label for="inputPassword4">Password</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <label for="inputAddress">Address</label>
            <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
        </div>
        <div class="form-group">
            <label for="inputAddress2">Address 2</label>
            <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputCity">City</label>
                <input type="text" class="form-control" id="inputCity">
            </div>
            <div class="form-group col-md-4">
                <label for="inputState">State</label>
                <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>...</option>
      </select>
            </div>
            <div class="form-group col-md-2">
                <label for="inputZip">Zip</label>
                <input type="text" class="form-control" id="inputZip">
            </div>
        </div>
        <div class="form-group">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
    </form>
</body>

</html>
<!-- temp1 -->
<form method="POST">
    <div class="form-row">
        <div class="col">
            <input type="text" class="form-control" id="title" name="title" placeholder="Title">
        </div>
    </div>
    <div class="form-row" style="background-color: aqua;">
        <!-- <div class="form-group col-md-8">
            <div id="editor"></div>
            <textarea name="code" id="id_code" cols="40" rows="30">code</textarea>
        </div>
        <div class="form-group col-md-4">
            <textarea name="input" class="form-control" id="id_input"></textarea>
        </div> -->
        <div class="form-group col-md-6">
            <label for="inputEmail4">Email</label>
            <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
        </div>
        <div class="form-group col-md-6">
            <label for="inputPassword4">Password</label>
            <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
        </div>
    </div>
</form>
<!-- temp1 end -->

IDEApp/templates/IDE/index.html
{% extends 'IDE/base.html' %} {%load static %} {% block content %}
<form method="POST" id="ide-form">
    {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <div class="row m-auto">
                <div class="col align-middle  float-left">
                    <div class="m-auto h1">
                        SUM
                    </div>
                </div>
                <select class="custom-select col-2 float-right mt-auto mb-auto mr-2" id="editor_theme">
                    <option value="twilight" selected>twilight</option>
                    <option value="terminal">terminal</option>
                    <option value="monokai">monokai</option>
                    <option value="dracula">dracula</option>
                </select>
                <select class="custom-select col-2 float-right mt-auto mb-auto mr-2" id="code_lang"
                    onchange="selectLang()">
                    <option value="c" selected>C</option>
                    <option value="cpp">C++</option>
                    <option value="py">Python</option>
                </select>
                <div class="float-right mt-auto mb-auto ">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown">
                            <i class="fas fa-cog"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <div class="dropdown-item">
                                <label class="form-check-label">
                                    <div class="d-inline my-auto py-auto">Wrap</div>
                                    <input type="checkbox" class="form-check-inline" id="text-wrap" checked>
                                </label>
                            </div>
                            <div class="dropdown-item">
                                <div class="d-inline my-auto py-auto">Font Size : <span id="span-font-range">16</span>
                                </div>
                                <input type="range" min="16" max="46" value="18" id="font-range"
                                    class="form-control-range">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="card-group">
                <div id="editor" class="m-0 p-0" style="width: 100%; height: 450px;"></div>
            </div>
            <textarea name="code" id="id_code" cols="100" rows="20" hidden></textarea>
        </div>
        <div class="card-footer">
            <div class="form-check custom-control float-left my-auto pl-0">
                <label class="form-check-label align-middle">
                    <div class="d-inline my-auto py-auto">Custom Input</div>
                    <input class="form-check-input ml-1 my-2 align-middle" type="checkbox" value="1" id="chk_input"
                        onchange="display()">
                    <div id="input" class="card input" style="display: none; ">
                        <p class="card-header bg-dark text-info">Input :</p>
                        <div class="card-body p-0">
                            <textarea name="input" id="id_input" cols="40 " rows="5 "></textarea>
                        </div>
                    </div>
                </label>
            </div>
            <div class="footer-btns" id="id_btns" aria-disabled="false">
                <button type="submit" class="btn btn-success float-right p-2 ml-2 mr-2rounded-right" value="submit"
                    onclick="setSubmit('submit')">
                    Submit
                </button>
                <button class="btn btn-info float-right p-2 ml-2 mr-2 rounded-right" value="run"
                    onclick="setSubmit('run')">Run</button>
            </div>
        </div>
    </div>
</form>
<div class="card my-3" id="output-card" style="margin: 0;padding: 0;">
    <div class="card-header">Output</div>
    <div class="card-body">
        <textarea id="textarea-output" class="shadow-textarea" style="height: auto;" readonly>  </textarea>
    </div>
</div>
<script src="{% static 'JS/index.js' %} " type="text/javascript " charset="utf-8 "></script>

{% endblock %}

IDEApp/templates/IDE/richText.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.ckeditor.com/ckeditor5/21.0.0/classic/ckeditor.js"></script>
</head>

<body>
    <form action="#" method="GET">
        <textarea id="editor" name="content">

        </textarea>
        <input type="submit" id="submit" name="submit"> </form>
</body>
<script>
    let editor;
    ClassicEditor
        .create(document.querySelector('#editor'))
        .then(newEditor => {
            editor = newEditor;
        })
        .catch(error => {
            console.error(error);
        });
    let button = document.getElementById("submit").addEventListener("click", function() {
        console.log(editor.getData());
    });
</script>

</html>

IDEApp/templates/IDE/temp.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</head>

<body>
    <form>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Email</label>
                <input type="email" class="form-control" id="inputEmail4">
            </div>
            <div class="form-group col-md-6">
                <label for="inputPassword4">Password</label>
                <input type="password" class="form-control" id="inputPassword4">
            </div>
        </div>
        <div class="form-group">
            <label for="inputAddress">Address</label>
            <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
        </div>
        <div class="form-group">
            <label for="inputAddress2">Address 2</label>
            <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputCity">City</label>
                <input type="text" class="form-control" id="inputCity">
            </div>
            <div class="form-group col-md-4">
                <label for="inputState">State</label>
                <select id="inputState" class="form-control">
                    <option selected>Choose...</option>
                    <option>...</option>
                </select>
            </div>
            <div class="form-group col-md-2">
                <label for="inputZip">Zip</label>
                <input type="text" class="form-control" id="inputZip">
            </div>
        </div>
        <div class="form-group">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
                    Check me out
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
    </form>


    <!-- actual form -->
    <form method="POST" id="ide-form">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <div>
            Title : <input type="text" name="title" id="id_title" value="Untitled" required>
        </div>
        <div>
            <p>Code :</p>
            <div id="editor"></div>
            <textarea name="code" id="id_code" cols="100" rows="20">code</textarea>
            <div class=" submit-btn ">
                <button type="submit " class="btn btn-info " name="run " value="run ">Run</button>
                <button type="submit " class="btn btn-success " name="submit " value="submit "
                    onclick="setSubmit() ">Submit</button>
            </div>
            <div class="chk_box">
                Custom input: <input type="checkbox " name="chk_input " id="chk_input " value="1 "
                    onchange="display() ">
            </div>
            <div id="input " class="input " style="display: none; ">
                <p>input :</p> <textarea name="input " id="id_input " cols="40 " rows="5 "></textarea>
            </div>
    </form>
    <!-- actual form end -->
</body>
<script>

    /* output editor */
    var output_editor = ace.edit("output");
    output_editor.resize();
    // output_editor.setOption("maxLines", 100);
    output_editor.setAutoScrollEditorIntoView(true);
    output_editor.renderer.setScrollMargin(10, 10, 10, 10);
    // output_editor.setOption("maxLines", 15);

    output_editor.setOptions({
        wrap: true,
        // readOnly: true,
        autoScrollEditorIntoView: true,
        copyWithEmptySelection: true,
        showPrintMargin: false, // hides the vertical limiting strip
        // maxLines: Infinity,
    });
    output_editor.setTheme("ace/theme/xcode");
    output_editor.session.setMode("ace/mode/c_cpp");
    output_editor.setValue("hello");
    /* output editor ends */
    function changeOutput(str) {
        output_editor = ace.edit("output");
        output_editor.resize();
        // output_editor.setOption("maxLines", 100);
        output_editor.setAutoScrollEditorIntoView(true);
        output_editor.renderer.setScrollMargin(10, 10, 10, 10);
        // output_editor.setOption("maxLines", 15);

        output_editor.setOptions({
            wrap: true,
            readOnly: true,
            autoScrollEditorIntoView: true,
            copyWithEmptySelection: true,
            showPrintMargin: false, // hides the vertical limiting strip
            // maxLines: Infinity,
        });
        output_editor.setTheme("ace/theme/xcode");
        output_editor.session.setMode("ace/mode/c_cpp");
        console.log("output" + str);
        output_editor.setValue(str);
        // send($('#ide-form'));
        return output_editor;
    }
    // function send(e) {
    //     document.getElementsByClassName('output')[0].innerHTML = '';
    //     console.log($('#chk_input').val());
    //     e.preventDefault();
    //     console.log('{% url ' + btnVal + ' %}');
    //     console.log(btnVal);
    //     $.ajax({
    //         type: 'POST',
    //         // url: '{% url "run" %}',
    //         url: '/IDEApp/' + btnVal + '/',
    //         data: {
    //             title: "hello", //$('#id_title').val(),
    //             code: editor.getValue(),
    //             chk_input: $('#chk_input').val(),
    //             csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
    //             inp: $('#id_input').val(),
    //             action: 'post'
    //         },
    //         success: function (json) {
    //             displayOutput(json.out);
    //             document.getElementsByClassName('ace_text-input')[0].setValue = json.out;
    //             // $(".output").prepend('<div class="col-md-6">' +
    //             //     '<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">' +
    //             //     '<div class="col p-4 d-flex flex-column position-static">' +
    //             //     '<p class="mb-auto">' + json.out + '</p>' +
    //             //     '</div>' +
    //             //     '</div>' +
    //             //     '</div>'
    //             // );
    //         },
    //         error: function (xhr, errmsg, err) {
    //             console.log("error");
    //             console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
    //         }
    //     });
    // }
    function displayOutput(str) {
        console.log(str + " HELLO OUTPUT");
        output_editor.setValue(str);
    }

</script>

</html>